In [1]:
import pandas as pd
import numpy as np

In [2]:
# Membaca dataset
df = pd.read_csv('data_tugas 2.csv')

# Menampilkan 5 data pertama
df.head()

,normalized-losses,make,bahan-bakar,jumlah-pintu,body-style,wheel-bases,length,width,height
0,?,alfa-romero,gas,two,convertible,88.6,168.8,64.1,48.8
1,?,alfa-romero,gas,two,convertible,88.6,168.8,64.1,48.8
2,?,alfa-romero,gas,two,hatchback,94.5,171.2,65.5,52.4
3,164,audi,gas,four,sedan,99.8,176.6,66.2,54.3
4,164,audi,gas,four,sedan,99.4,176.6,66.4,54.3

In [3]:
# Mengecek jumlah data hilang
missing = df.isnull().sum()

# Menampilkan hasil
print(missing)

normalized-losses     0
make                  4
bahan-bakar          13
jumlah-pintu         16
body-style           12
wheel-bases           3
length                8
width                 5
height                4
dtype: int64

In [4]:
kategori = ['make', 'bahan-bakar', 'jumlah-pintu', 'body-style']

In [5]:
df[kategori] = df[kategori].fillna('unknown')

In [6]:
for col in kategori:
    print("\nKolom:", col)
    print(df[col].value_counts())

Kolom: make
make
toyota           32
mazda            17
nissan           17
honda            13
mitsubishi       12
volkswagen       12
volvo            11
subaru           11
peugot           11
dodge             9
mercedes-benz     8
bmw               8
plymouth          7
audi              7
saab              6
porsche           4
unknown           4
isuzu             4
alfa-romero       3
chevrolet         3
jaguar            3
renault           2
mercury           1
Name: count, dtype: int64

Kolom: bahan-bakar
bahan-bakar
gas        173
diesel      19
unknown     13
Name: count, dtype: int64

Kolom: jumlah-pintu
jumlah-pintu
four       101
two         86
unknown     16
?            2
Name: count, dtype: int64

Kolom: body-style
body-style
sedan          88
hatchback      67
wagon          24
unknown        12
hardtop         8
convertible     6
Name: count, dtype: int64

In [7]:
numerik = ['length', 'width', 'height']

In [8]:
rata_rata = df[numerik].mean()
print(rata_rata)

length    173.902538
width      65.931000
height     53.737313
dtype: float64

In [9]:
df[numerik] = df[numerik].fillna(rata_rata)

In [10]:
df['wheel-bases-normalized'] = (
    (df['wheel-bases'] - df['wheel-bases'].min()) /
    (df['wheel-bases'].max() - df['wheel-bases'].min())
)

# Menampilkan hasil
df[['wheel-bases', 'wheel-bases-normalized']].head()

   wheel-bases  wheel-bases-normalized
0         88.6                0.058309
1         88.6                0.058309
2         94.5                0.230321
3         99.8                0.384840
4         99.4                0.373178

In [11]:
for col in numerik:
    df[col + '_zscore'] = (df[col] - df[col].mean()) / df[col].std()

# Menampilkan hasil
df[['length_zscore', 'width_zscore', 'height_zscore']].head()

   length_zscore  width_zscore  height_zscore
0      -0.428526     -0.867630      -2.038094
1      -0.428526     -0.867630      -2.038094
2      -0.226967     -0.204232      -0.552035
3       0.226541      0.127467       0.232274
4       0.226541      0.222238       0.232274

In [12]:
df.to_csv('hasil_data_preparation.csv', index=False)